### ISSUE TITLE
persian unicode problem

### ISSUE THREAD

**Issue by hra1368** [javalite/activeweb-simple#4]
when type persian/arabic text in ftl file then see incorrect text in browser. 
defualt_layout.ftl
<#setting url_escaping_charset='utf-8'>

web.xml:
```
        <init-param>
            <param-name>encoding</param-name>
            <param-value>UTF-8</param-value>
        </init-param>
```
set above config also.
please advise me. thanks

**Comment by ipolevoy** [comment]
Please, include what you type and screenshot of what you see

**Comment by hra1368** [comment]
![untitled](https://user-images.githubusercontent.com/9411899/26897379-9bdd9c46-4bdd-11e7-97fa-aca5dddc9e1a.png)
![untitled2](https://user-images.githubusercontent.com/9411899/26897384-9f5c0b96-4bdd-11e7-9c2c-25f9feac7c49.png)

**Comment by hra1368** [comment]
typed:
حمید رضا عبدی
generated HTML:
<p>Ø­Ù…ÛŒØ¯ Ø±Ø¶Ø§ Ø¹Ø¨Ø¯ÛŒ.</p>

**Comment by ipolevoy** [comment]
@hra1368 can you please fork the activeweb-simple, make your changes and send a pull request so I had access to your exact code?

**Comment by hra1368** [comment]
I think problem from freemarker. how set encoding in freemarker pragmatically?

**Comment by hra1368** [comment]
set 
        getConfiguration().setURLEscapingCharset("UTF-8");
        getConfiguration().setEncoding(Locale.getDefault(),"UTF-8");
in  FreeMarkerConfig class
problem is solve. thanks

**Comment by ipolevoy** [comment]
@hra1368 :)
