### ISSUE TITLE
Maven error can not find 2.1-SNAPSHOT

### ISSUE THREAD

**Issue by AndreasHohnholt** [javalite/activeweb-simple#8]
Maven can not resolve:

<activejdbc.version>2.1-SNAPSHOT</activejdbc.version>
<activeweb.version>2.1-SNAPSHOT</activeweb.version>

see: https://mvnrepository.com/artifact/org.javalite/activejdbc-instrumentation

**Comment by ipolevoy** [comment]
@AndreasHohnholt this is a valid issue, sorry for inconvenience. I added a snapshot repos to the pom, should be working now. Please, pull and  try again.
