### ISSUE TITLE
jetty:run does not work because of sql migration error

### ISSUE THREAD

**Issue by AndreasHohnholt** [javalite/activeweb-simple#9]
Fails with this msg:

[ERROR] Failed to execute goal org.javalite:db-migrator-maven-plugin:2.0:migrate (dev_migrations) on project activeweb-simple: Execution dev_migrations of goal org.javalite:db-migrator-maven-plugin:2.0:migrate failed: Migration for version 20110404044351 failed, rolling back and terminating migration. com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Query was empty -> [Help 1]

Stacktrace:
[ERROR] Error executing migration file: D:\activeweb-simple\src\migrations\20110404044351_create_books_table.sql
java.lang.RuntimeException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Query was empty

**Comment by ipolevoy** [comment]
should be fixed now, try again.

**Comment by ipolevoy** [comment]
@AndreasHohnholt did this work for you?

**Comment by AndreasHohnholt** [comment]
@ipolevoy yes now it works fpr me 👍
